# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: backend-black
        name: backend-black
        entry: backend/.venv/bin/black --config backend/pyproject.toml --check
        language: system
        files: ^backend/.*.(py|pyi)$

      - id: backend-isort
        name: backend-isort
        entry: backend/.venv/bin/isort --sp backend/pyproject.toml --check-only
        language: system
        files: ^backend/.*.(py|pyi)$

      - id: backend-mypy
        name: backend-mypy
        entry: backend/.venv/bin/mypy --config-file backend/setup.cfg backend
        language: system
        files: ^backend/.*.(py|pyi)$
        pass_filenames: false
