# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint

  # Тут свои прекоммиты, которые запускаются в отдельных docker-контейнерах.
  # Для них нужно отрезать папку (название проекта) в начале каждого аргумента, что делает sed
  #
  # ATTENTION: Если вылетает ошибка 123 или 1, вероятнее всего, контейнер не запущен
  - repo: local
    hooks:
      # ========================================= Backend ==========================================
      - id: backend-black
        name: backend-black
        entry: bash -c 'echo "$@" | sed "s/^backend\///g" | sed "s/\sbackend\// /g" |
                xargs docker-compose exec -T backend black --check' --
        verbose: true
        language: system
        files: ^backend/.*.(py|pyi)$

      - id: backend-isort
        name: backend-isort
        entry: bash -c 'echo "$@" | sed "s/^backend\///g" | sed "s/\sbackend\// /g" |
                xargs docker-compose exec -T backend isort --sp pyproject.toml --check-only' --
        language: system
        files: ^backend/.*.(py|pyi)$

      # Mypy работает со всеми файлами
      - id: backend-mypy
        name: backend-mypy
        entry: docker-compose exec -T backend mypy --show-error-codes --config-file setup.cfg .
        language: system
        files: ^backend/.*.(py|pyi)$
        pass_filenames: false

      - id: backend-flake8
        name: backend-flake8
        entry: bash -c 'echo "$@" | sed "s/^backend\///g" | sed "s/\sbackend\// /g" |
                xargs docker-compose exec -T backend flake8 --config setup.cfg' --
        language: system
        files: ^backend/.*.(py|pyi)$
